### ISSUE TITLE
MobX for React Native Navigation v2.0?

### ISSUE THREAD

**Issue by santanu4ver** [kanzitelli/react-native-navigation-mobx-boilerplate#4]
Hi there!

Is there any plan to put on a boilerplate for [v2]RNN soon? 

So far I tried to follow setup with [v2], also used the the util class to provide Provider - but having following error to the screen classes:

> Error: MobX injector: Store 'someStoreFile' is not available! Make sure it is provided by some Provider

Thanks!

**Comment by kanzitelli** [comment]
Hello, @santanu4ver!

Thank you for your comment. I have stopped using RN long time ago during to limitations of it when trying to implement something more professional for both iOS & Android. Therefore I am not fully informed what changes were made to v2 of RNN and can not give you any expertise following this error. I apologize about it!

**Comment by santanu4ver** [comment]
Ah! Thank you for replying on that. Although, I'm newbie to RN and RNN - I have found this of your repo at RNN issue thread.

So are you working on native directly, or you're on some new language? (if you don't mind to share @kanzitelli )

Thank you! I'm closing this issue anyway.

**Comment by kanzitelli** [comment]
Hi again @santanu4ver!

Yes, I am developing native apps for iOS in Swift and Android in Kotlin. I have also tried Flutter for Google. And both RN and Flutter are good for simple apps, for example, displaying info in List, but when I need to implement something using Media it was a challenge for me, so that's why I have come back to native development. If your goal is to develop simple fast apps, you can take a look at Expo for RN, I used to make fast prototypes :) 

Good luck! If you have anything to ask, please feel free to do it!

**Comment by santanu4ver** [comment]
Hey thank you @kanzitelli for some insight! 

Personally, I developed iOS on Swift. For hybrid development I used to with Adobe AIR. Since, RN is considerably faster when it comes about hybrid, I thought to try with RN. But as a newcomer, definitely I found maintaining versions here and there is clearly a pain. Like, when you want to someone's code to run with latest versions of RN, attaching newer APIs to the project etc. 

I must confess, supplying version and dependencies a clear cut pain in a* in RN development - where nothing is fix, and things keep changing time to time. In that regard, native development is much practical and safer. 

Anyway, as my new quest, I will keep trying to fix a logical/working template for mobx/rnn for some time, let's see.. 

Thanks again!
